# Generated by Django 6.0.3 on 2026-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.TextField()),
                ('poster_title', models.CharField(max_length=300)),
                ('colour_theme', models.TextField()),
                ('visual_elements', models.TextField()),
                ('layout_structure', models.TextField()),
                ('typography', models.TextField()),
                ('ai_prompt', models.TextField()),
                ('platform_trends', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
